version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run: echo "BUILD"
  
  test:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run: echo "TEST"
      - run: git reset --soft HEAD~1
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two